export {default as FirstSection} from './FirstSection'
export {default as SecondSection} from './SeconSection'
export {default as ThirdSection} from './ThirdSection'
export {default as FourthSection} from './FourthSection'
export {default as FifthhSection} from './FifthSection'